In [1]:
import numpy as np

In [7]:
##Q-1 Create a null vector of size 10 but the fifth value which is 1.
ar=np.zeros([10],dtype="int")
ar[4]=1
ar

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [11]:
#Q-2 Ask user to input two numbers a, b. Write a program to generate a random array of
# shape (a, b) and print the array and avg of the array.
a=int(input("Enter row "))
b=int(input("Enter column "))
na=np.random.rand(a,b)
print(na)
print(na[0][0])

Enter row 3
Enter column 4
[[0.76257667 0.48770727 0.32452705 0.84246536]
 [0.21169226 0.63752078 0.19820296 0.18265238]
 [0.86492623 0.27154979 0.08620538 0.38126249]]
0.7625766707491415


In [23]:
#Q-3Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array
# shape as (a,b) as parameter to function.
c=int(input("Enter row "))
d=int(input("Enter column "))
ma=np.ones((c,d))
for i in range(1,c-1):
  for j in range(1,d-1):
    ma[i][j]=0

print(ma)

Enter row 4
Enter column 4
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [38]:
###Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.
v=np.random.rand(10)
v1 = np.random.uniform(low=0.0001, high=0.9999, size=10)
v1

array([0.97884056, 0.21512587, 0.03601075, 0.90287662, 0.30680874,
       0.23457979, 0.57284455, 0.85987661, 0.52576904, 0.46988261])

In [52]:
###Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it.
r=np.zeros((4,4))
for i in range(4):
    r[i][i]=1
print(r)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [50]:
r2=np.eye(4)
r2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [62]:
###Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.
# e=np.random.uniform(low=0,high=4,size=(5,5))
# e
e1=np.tile(np.arange(5), (5, 1))
e1

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [104]:
#Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing
# coordinates, and coordinates of a point as array is given. Create an array of distance of each
# point in the random vectros from the given point. Distance array should be interger type.
t=np.random.randint(low=1,high=101,size=(10,2))
print(t)
gp = np.array([100,100])
distances = np.sqrt(np.sum((t - gp) ** 2, axis=1))
distances.astype("int")

[[94 32]
 [80 88]
 [20 62]
 [33 96]
 [48  3]
 [42  4]
 [17 61]
 [99  3]
 [66 50]
 [81 84]]


array([ 68,  23,  88,  67, 110, 112,  91,  97,  60,  24])

In [113]:
###Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
kl=np.arange(1,337).reshape(6,7,8)
# kl[1][5][3]
index=np.where(kl==100)
print(index)


(array([1]), array([5]), array([3]))


In [116]:
# Q-9: Arrays You are given a space separated list of numbers. Your task is to print a reversed NumPy array
# with the element type float.
arr=np.array([1,2,3,4,-8,-10])
arr[::-1].astype("float")

array([-10.,  -8.,   4.,   3.,   2.,   1.])

In [119]:
# Q-10: Elements count
# Count the number of elements of a numpy array.
arr2=np.array([1,2,3,4,-8,-10])
print(arr2.size)

6
